### ISSUE TITLE
Web app features > Fetch data > Svelte

### ISSUE THREAD

**Issue by GauBen** [matschik/component-party.dev#183]
Hey!

I feel like the current "Fetch data" snippet does not do Svelte justice as there is a special [`{#await}`](https://svelte.dev/tutorial/await-blocks) tag for that matter. The whole snippet can be shortened to:

```svelte
<script>
  // Can still be imported from a file to keep the structure
  async function fetchData() {
    const response = await fetch("https://randomuser.me/api/?results=3");
    const { results } = await response.json();
    return results;
  }
</script>

{#await fetchData()}
  <p>Fetching users...</p>
{:then users}
  <ul>
    {#each users as user}
      <li>
        <img src={user.picture.thumbnail} alt="user" />
        <p>
          {user.name.first}
          {user.name.last}
        </p>
      </li>
    {/each}
  </ul>
{:catch}
  <p>An error occurred while fetching users</p>
{/await}
```

I will open a PR if this change is accepted

**Comment by benmccann** [comment]
In reality though, we wouldn't encourage that code either, but to use SvelteKit: https://kit.svelte.dev/docs/load

The "Router link" and "Routing" examples demonstrate using SvelteKit. I think this one probably should too for consistency and to follow best practices

**Comment by matschik** [comment]
If we include meta frameworks, it would be too much work to maintain it across all frameworks.
Component Party focus on the frameworks themselves, not their ecosystem.
We just included routing to show a preview of the main feature of meta frameworks and to showcase them.

**Comment by benmccann** [comment]
Going back to the original discussion then. @matschik said in https://github.com/matschik/component-party.dev/issues/186#issuecomment-1728323498:

> The Fetch data example is too much different from other frameworks. It's also a great way to show how to reuse code in Svelte 5. In real world app, await syntax is rarely used to fetch data for a lot of reasons: see [Svelte TanStack query](https://tanstack.com/query/v4/docs/svelte/overview) for instance.


I suppose it helps for comparing frameworks if they're written in the same style, but at the same time the code as it's written now doesn't seem how you'd write it idiomatically in Svelte to me. I don't know if I've ever seen anyone use stores to track fetch state in this manner before in Svelte. I'm not super familiar with TanStack query or why they made the design choices they did. I believe that library also supports React and so my naive guess would be that it was written that way to mirror the React version rather than because it's how someone really familiar with Svelte would write it. I'd be curious to hear the reason why you say `await` should be avoided in the real world.

**Comment by matschik** [comment]
The main reason is to have a better experience when comparing Svelte fetch data snippet.
The second reason is, when you want to handle your query state only client side, I end up doing something similar to TanStack query. That's why Svelte Query was made originally instead of reinventing the wheel: https://github.com/SvelteStack/svelte-query
Then they merged this work into TanStack Query via `@tanstack/svelte-query`.

In short, this snippet is for client data fetching only, and the best way to handle client data fetching state I know is a pattern similar to `@tanstack/svelte-query`. This method is used into the other frameworks to have a much better comparison. It's not fair to have 2 files in the other frameworks and only 1 file for Svelte snippets.

And for Svelte 5, it's an opportunity to show one of the main reason Svelte 5 was made: more simple reusable code.

**Comment by sacrosanctic** [comment]
> It's not fair to have 2 files in the other frameworks and only 1 file for Svelte snippets.

A quick glance at the snippets from other frameworks show that some of them only use 1 file.
